"""add product, order, donation, contact tables

Revision ID: 1cafc4a0d3df
Revises: 5eef57e220c8
Create Date: 2025-07-13 11:25:03.332014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cafc4a0d3df'
down_revision: Union[str, Sequence[str], None] = '5eef57e220c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
